services:
  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  erp-service:
    build:
      context: .
      dockerfile: erp-service/Dockerfile
    container_name: erp-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "50051:50051"

  ecommerce-service:
    build:
      context: .
      dockerfile: ecommerce-service/Dockerfile
    container_name: ecommerce-service
    depends_on:
      rabbitmq:
        condition: service_healthy
      erp-service:
        condition: service_started
    ports:
      - "3000:3000"

  crm-service:
    build:
      context: .
      dockerfile: crm-service/Dockerfile
    container_name: crm-service
    depends_on:
      rabbitmq:
        condition: service_healthy

  logging-service:
    build:
      context: .
      dockerfile: logging-service/Dockerfile
    container_name: logging-service
    depends_on:
      rabbitmq:
        condition: service_healthy