FROM node:23-alpine
WORKDIR /app
RUN npm install -g @nestjs/cli
COPY logging-service/package.json logging-service/tsconfig.json ./
RUN npm install
COPY logging-service/src ./src
RUN npm run build
CMD ["npm", "run", "start"]