FROM node:23-alpine
WORKDIR /app
RUN npm install -g @nestjs/cli
COPY ecommerce-service/package.json ecommerce-service/tsconfig.json ./
RUN npm install
COPY libs/proto ./libs/proto
COPY ecommerce-service/src ./src
RUN npm run build
CMD ["npm", "run", "start"]