FROM node:23-alpine
WORKDIR /app
RUN npm install -g @nestjs/cli
COPY crm-service/package.json crm-service/tsconfig.json ./
RUN npm install
COPY libs/proto ./libs/proto
COPY ecommerce-service/src ./src
RUN npm run build
CMD ["node", "dist/main.js"]