FROM node:23-alpine
WORKDIR /app
RUN npm install -g @nestjs/cli
COPY erp-service/package.json erp-service/tsconfig.json ./
RUN npm install
COPY libs/proto ./libs/proto
COPY erp-service/src ./src
RUN npm run build
CMD ["npm", "run", "start"]
